"""Write src/lib/artAssets.ts: static imports for every rendered image."""
import os
ROOT = os.path.join(os.path.dirname(__file__), "..")
art = os.path.join(ROOT, "src", "assets", "art")
worlds = sorted(f[:-4] for f in os.listdir(art) if f.endswith(".jpg"))
chars = sorted(f[:-4] for f in os.listdir(os.path.join(art, "characters")) if f.endswith(".jpg"))
ident = lambda s: "c_" + s.replace("-", "_")
lines = ["// Generated by art-src/gen_index.py — do not edit by hand.", "/* eslint-disable */"]
lines += [f'import w_{w} from "@/assets/art/{w}.jpg";' for w in worlds]
lines += [f'import {ident(c)} from "@/assets/art/characters/{c}.jpg";' for c in chars]
lines += ["", "type Img = string | { src: string };", "const u = (i: Img) => (typeof i === \"string\" ? i : i.src);", ""]
lines += ["export const WORLD_ART: Record<string, string> = {"] + [f"  {w}: u(w_{w})," for w in worlds] + ["};", ""]
lines += ["export const CHARACTER_ART: Record<string, string> = {"] + [f'  "{c}": u({ident(c)}),' for c in chars] + ["};", ""]
open(os.path.join(ROOT, "src", "lib", "artAssets.ts"), "w").write("\n".join(lines))
print(len(worlds), "worlds,", len(chars), "characters")
