// Generated by art-src/gen_index.py — do not edit by hand.
/* eslint-disable */
import w_academy from "@/assets/art/academy.jpg";
import w_blocks from "@/assets/art/blocks.jpg";
import w_garden from "@/assets/art/garden.jpg";
import w_kingdom from "@/assets/art/kingdom.jpg";
import w_sea from "@/assets/art/sea.jpg";
import w_space from "@/assets/art/space.jpg";
import w_stadium from "@/assets/art/stadium.jpg";
import w_train from "@/assets/art/train.jpg";
import c_archive from "@/assets/art/characters/archive.jpg";
import c_booth_voice from "@/assets/art/characters/booth-voice.jpg";
import c_bramble_golem from "@/assets/art/characters/bramble-golem.jpg";
import c_conductor_ferro from "@/assets/art/characters/conductor-ferro.jpg";
import c_felix_marsh from "@/assets/art/characters/felix-marsh.jpg";
import c_groundskeeper_ada from "@/assets/art/characters/groundskeeper-ada.jpg";
import c_ilo_navigator from "@/assets/art/characters/ilo-navigator.jpg";
import c_ines_snowfield from "@/assets/art/characters/ines-snowfield.jpg";
import c_kestrel_vane from "@/assets/art/characters/kestrel-vane.jpg";
import c_lumen_moth from "@/assets/art/characters/lumen-moth.jpg";
import c_marisol_reyes from "@/assets/art/characters/marisol-reyes.jpg";
import c_moss_gardener from "@/assets/art/characters/moss-gardener.jpg";
import c_nell_cartographer from "@/assets/art/characters/nell-cartographer.jpg";
import c_number_nine from "@/assets/art/characters/number-nine.jpg";
import c_old_barnaby from "@/assets/art/characters/old-barnaby.jpg";
import c_pip_builder from "@/assets/art/characters/pip-builder.jpg";
import c_professor_quill from "@/assets/art/characters/professor-quill.jpg";
import c_queen_alder from "@/assets/art/characters/queen-alder.jpg";
import c_sea_captain from "@/assets/art/characters/sea-captain.jpg";
import c_sorrel_greenwitch from "@/assets/art/characters/sorrel-greenwitch.jpg";
import c_star_admiral from "@/assets/art/characters/star-admiral.jpg";
import c_the_gaffer from "@/assets/art/characters/the-gaffer.jpg";
import c_the_librarian from "@/assets/art/characters/the-librarian.jpg";
import c_tin_sentinel from "@/assets/art/characters/tin-sentinel.jpg";
import c_tomas_ri from "@/assets/art/characters/tomas-ri.jpg";
import c_wren_ashby from "@/assets/art/characters/wren-ashby.jpg";

type Img = string | { src: string };
const u = (i: Img) => (typeof i === "string" ? i : i.src);

export const WORLD_ART: Record<string, string> = {
  academy: u(w_academy),
  blocks: u(w_blocks),
  garden: u(w_garden),
  kingdom: u(w_kingdom),
  sea: u(w_sea),
  space: u(w_space),
  stadium: u(w_stadium),
  train: u(w_train),
};

export const CHARACTER_ART: Record<string, string> = {
  "archive": u(c_archive),
  "booth-voice": u(c_booth_voice),
  "bramble-golem": u(c_bramble_golem),
  "conductor-ferro": u(c_conductor_ferro),
  "felix-marsh": u(c_felix_marsh),
  "groundskeeper-ada": u(c_groundskeeper_ada),
  "ilo-navigator": u(c_ilo_navigator),
  "ines-snowfield": u(c_ines_snowfield),
  "kestrel-vane": u(c_kestrel_vane),
  "lumen-moth": u(c_lumen_moth),
  "marisol-reyes": u(c_marisol_reyes),
  "moss-gardener": u(c_moss_gardener),
  "nell-cartographer": u(c_nell_cartographer),
  "number-nine": u(c_number_nine),
  "old-barnaby": u(c_old_barnaby),
  "pip-builder": u(c_pip_builder),
  "professor-quill": u(c_professor_quill),
  "queen-alder": u(c_queen_alder),
  "sea-captain": u(c_sea_captain),
  "sorrel-greenwitch": u(c_sorrel_greenwitch),
  "star-admiral": u(c_star_admiral),
  "the-gaffer": u(c_the_gaffer),
  "the-librarian": u(c_the_librarian),
  "tin-sentinel": u(c_tin_sentinel),
  "tomas-ri": u(c_tomas_ri),
  "wren-ashby": u(c_wren_ashby),
};
